- id: normalize-punctuation
  name: normalize-punctuation
  description: "Normalize punctuation in Markdown files."
  entry: normalize-punctuation
  types_or: [md]
  language: rust
  minimum_pre_commit_version: 3.3.3
